
using Nanook.NKit;
using System;
using System.IO;
using Xunit;

namespace NKit.Tests.Full.Wiped
{
    public partial class WipedImage_WiiU_Tests : WipedImageTestsBase
    {
        //CAT-I      / WUX       / 23.4GiB / Decrypted SI partition, CommonDev key for game ticket
        [Fact]
        public void JvvH_PNG_V_wux_Expand()
        {
            string fileName = @"JvvH_PNG-V.wux";
            string inPath = Path.GetFullPath(Path.Combine(@"../../../../../WipedImages", "WiiU"));
            string outFolderName = $"WiiU_JvvH_PNG_V_wux_Expand_{Guid.NewGuid():N}";
            string basePath = Directory.CreateDirectory(Path.Combine(".", outFolderName)).FullName;
            string dats = @"";
            string keys = @"../../../../../WipedImages/_keys";
            string fixInfo = @"";
            string fixFiles = @"";

            SystemPresetSettings presets = base.CreatePresets("Expand", @"", inPath, fileName, outFolderName, dats, keys, fixInfo, fixFiles);
            presets.System = SystemType.WiiU;

            NKitTaskResults t = base.ProcessImage(presets);
            NKitStepResult r = t.StepResults[0].Result;
            SourceFile f = t.Source;
            IStepInfo i = r.StepInfo;
            Scan s = t.Scan;

            ////////////////////////////////////////
            // Source File
            ////////////////////////////////////////
            Assert.NotNull(f);
            Assert.Equal(inPath.TrimEnd('\\', '/'), f.BasePath.TrimEnd('\\', '/'));
            Assert.NotNull(f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("JvvH_PNG-V.wux", f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("JvvH_PNG-V", f.CleanName);
            Assert.Equal("JvvH_PNG-V", f.Name);
            Assert.Equal(SourceImageType.Wux, f.ImageType);
            Assert.Equal(SourceFileResult.Valid, f.Status);
            Assert.Equal(SystemType.WiiU, f.SystemType);
            Assert.False(f.IsArchive);
            Assert.False(f.IsArchived);
            Assert.False(f.IsDeleted);
            Assert.False(f.IsFolderMode);
            Assert.False(f.IsSplitArchive);
            Assert.False(f.IsSplitImage);
            Assert.Equal(0x0L, f.Length);
            Assert.Equal(1, f.ImageFiles.Length);
            Assert.Equal("JvvH_PNG-V.wux", f.ImageFiles[0].FileName);
            Assert.Equal("JvvH_PNG-V", f.ImageFiles[0].NameOnly);
            Assert.Equal(".wux", f.ImageFiles[0].Extension);
            Assert.Equal(0x3f8000L, f.ImageFiles[0].Size);
            Assert.False(f.ImageFiles[0].IsArchived);
            Assert.Equal(SourceArchiveType.None, f.ArchiveType);
            Assert.Null(f.ArchiveFiles);
            Assert.Null(f.Key);
            // f.IndexFile IndexFile Test
            Assert.Null(f.IndexFile);

            ////////////////////////////////////////
            // Step Info
            ////////////////////////////////////////
            Assert.NotNull(i);
            Assert.True(i.CanCrc);
            Assert.True(i.CanHash);
            Assert.False(i.CreateInChecksum);
            Assert.False(i.CreateOutChecksum);
            Assert.True(i.CreateScan);
            Assert.False(i.DeleteSourceCandidate);
            Assert.True(i.FullScan);
            Assert.True(i.IsExpand);
            Assert.False(i.IsFix);
            Assert.False(i.IsLossy);
            Assert.True(i.WriteImage);
            Assert.Equal("Expand-Image", i.Name);
            Assert.Equal(OutputType.Image, i.OutputType);
            Assert.False(i.ReqChk);
            Assert.False(i.ReqPatch);
            Assert.Equal(TaskType.Expand, i.StepType);
            Assert.Equal(VerifyMethod.NoVerify, i.VerifyMethod);
            Assert.Null(i.VerifyChecksums);
            Assert.NotNull(i.Config);
            Assert.Equal("iso", i.Config);
            Assert.NotNull(i.ImageConfig);
            Assert.Equal("", i.ImageConfig);
            Assert.NotNull(i.SrcParts);
            Assert.Equal(1, i.SrcParts.Length);
            Assert.Equal(0x0L, i.SrcParts[0].Size);
            Assert.NotNull(i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Equal("", i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Null(i.SrcParts[0].FileName);

            ////////////////////////////////////////
            // Source Scan
            ////////////////////////////////////////
            Assert.Null(i.SrcScan);

            ////////////////////////////////////////
            // Source DatItem
            ////////////////////////////////////////
            Assert.Null(i.DatMatch);

            ////////////////////////////////////////
            // Step Result
            ////////////////////////////////////////
            Assert.NotNull(r);
            Assert.Equal("JvvH_PNG-V.iso", r.FinalName);
            Assert.Null(r.ChkCompared);
            Assert.Null(r.InFileParts);
            Assert.NotNull(r.OutFileParts);
            Assert.Equal(1, r.OutFileParts.Length);
            Assert.Equal(0x5d3a00000L, r.OutFileParts[0].Size);
            Assert.NotNull(r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:132EC10F", r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.NotNull(r.OutFileParts[0].FileName);
            Assert.Equal("JvvH_PNG-V.iso~", r.OutFileParts[0].FileName);
            Assert.NotNull(r.ResultCrc);
            Assert.Equal(0x132ec10fU, r.ResultCrc.Value);
            Assert.NotNull(r.ResultSize);
            Assert.Equal(0x5d3a00000L, r.ResultSize.Value);
            Assert.NotNull(r.Scan);
            Assert.NotNull(r.StepInfo);
            Assert.Equal(VerifyResult.Unverified, r.VerifyResult);
            Assert.Equal("NoVerify", r.VerifyType);

            ////////////////////////////////////////
            // StepResult DatItem
            ////////////////////////////////////////
            Assert.Null(r.MatchedDatItem);

            ////////////////////////////////////////
            // Task Result
            ////////////////////////////////////////
            Assert.Equal(ContainerType.Wux, t.ContainerType);
            Assert.Equal(SystemType.WiiU, t.System);
            Assert.Equal(TaskType.Expand, t.Task);
            Assert.Equal(0x5d3a00000L, t.Size);
            Assert.Equal(0x132ec10fU, t.CRC);
            Assert.Equal(0xe0c4c08cU, t.DecryptedCrc);
            Assert.Equal(VerifyResult.Unverified, t.VerifyResult);
            Assert.Equal(inPath.TrimEnd('\\', '/'), t.InFilePath.TrimEnd('\\', '/'));
            Assert.Equal(basePath.TrimEnd('\\', '/'), t.OutPath.TrimEnd('\\', '/'));
            Assert.NotNull(t.Name);
            Assert.Equal("JvvH_PNG-V", t.Name);
            Assert.NotNull(t.VerifyType);
            Assert.Equal("NoVerify", t.VerifyType);
            Assert.NotNull(t.VerifyChecksum);
            Assert.Equal("", t.VerifyChecksum);
            Assert.Null(t.DatMatch);
            Assert.Null(t.ErrorMsg);
            Assert.NotNull(t.OutFileName);
            Assert.Equal("JvvH_PNG-V.iso", t.OutFileName);
            Assert.Null(t.OutKeyFilePath);
            Assert.NotNull(t.OutScanFilePath);
            Assert.Equal(Path.Combine(basePath, "JvvH_PNG-V.nkit.yaml"), t.OutScanFilePath);
            Assert.False(t.HasEncryption);
            Assert.True(t.SupportsEncryption);
            Assert.False(t.ImageSkipped);
            Assert.Null(t.Key);
            Assert.NotNull(t.StepFiles);
            Assert.Equal(1, t.StepFiles.Count);
            Assert.Equal(0x5d3a00000L, t.StepFiles[0].Size);
            Assert.False(t.StepFiles[0].IsIndex);
            Assert.True(t.StepFiles[0].IsImageName);
            Assert.NotNull(t.StepFiles[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:132EC10F", t.StepFiles[0].Checksums.ToString(true, true));
            Assert.NotNull(t.StepFiles[0].FileName);
            Assert.Equal("JvvH_PNG-V.iso~", t.StepFiles[0].FileName);

            ////////////////////////////////////////
            // Result Scan
            ////////////////////////////////////////
            Assert.NotNull(t.Scan);
            Assert.NotNull(t.Scan.Name);
            Assert.Equal("JvvH_PNG-V", t.Scan.Name);
            Assert.Equal(SystemType.WiiU, f.SystemType);
            Assert.Equal(0x132ec10fU, t.Scan.Crc);
            Assert.Equal(0xe0c4c08cU, t.Scan.CrcDecrypted);
            Assert.Equal(0x5d3a00000L, t.Scan.Size);
            Assert.Equal(818, t.Scan.VirtualFsTotalFileCount);
            Assert.Equal(88, t.Scan.VirtualFsTotalFoldersCount);
            Assert.NotNull(t.Scan.Properties["System"].ToXmlValue());
            Assert.Equal("WiiU", t.Scan.Properties["System"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Media"].ToXmlValue());
            Assert.Equal("WUD", t.Scan.Properties["Media"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Type"].ToXmlValue());
            Assert.Equal("Dev", t.Scan.Properties["Type"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Size"].ToXmlValue());
            Assert.Equal("5D3A00000", t.Scan.Properties["Size"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["CRC"].ToXmlValue());
            Assert.Equal("132EC10F", t.Scan.Properties["CRC"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal("E0C4C08C", t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal(19, t.Scan.Areas.Count);
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[0].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal(AreaType.ImageHeader, t.Scan.Areas[0].Type);
            Assert.Equal(0x4f8f4f55U, t.Scan.Areas[0].Crc);
            Assert.Equal(0x4f8f4f55U, t.Scan.Areas[0].CrcDecrypted);
            Assert.Equal(0x18000L, t.Scan.Areas[0].Size);
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Partitions"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[1].AreaInfo.Properties["Partitions"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[1].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["KeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[1].AreaInfo.Properties["KeyCrc"].ToXmlValue());
            Assert.Equal(AreaType.PartitionTable, t.Scan.Areas[1].Type);
            Assert.Equal(0x690f4e9bU, t.Scan.Areas[1].Crc);
            Assert.Equal(0x690f4e9bU, t.Scan.Areas[1].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[1].Size);
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Si", t.Scan.Areas[2].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.Equal("SI", t.Scan.Areas[2].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("0000000000000000", t.Scan.Areas[2].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[2].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[2].Type);
            Assert.Equal(0xefd2e829U, t.Scan.Areas[2].Crc);
            Assert.Equal(0xefd2e829U, t.Scan.Areas[2].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[2].Size);
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[3].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[3].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal(AreaType.FstBlock, t.Scan.Areas[3].Type);
            Assert.Equal(0x46080f09U, t.Scan.Areas[3].Crc);
            Assert.Equal(0x46080f09U, t.Scan.Areas[3].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[3].Size);
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[4].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[4].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[4].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[4].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("555055556CD37D55", t.Scan.Areas[4].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[4].Type);
            Assert.Equal(0x8aae4144U, t.Scan.Areas[4].Crc);
            Assert.Equal(0x8aae4144U, t.Scan.Areas[4].CrcDecrypted);
            Assert.Equal(0x400000L, t.Scan.Areas[4].Size);
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[5].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[5].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[5].Type);
            Assert.Equal(0xcc9bca22U, t.Scan.Areas[5].Crc);
            Assert.Equal(0xcc9bca22U, t.Scan.Areas[5].CrcDecrypted);
            Assert.Equal(0xbfbd0000L, t.Scan.Areas[5].Size);
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Game", t.Scan.Areas[6].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.Equal("GM555055556CD37D55555555555555", t.Scan.Areas[6].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("555055556CD37D55", t.Scan.Areas[6].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[6].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[6].Type);
            Assert.Equal(0x5cc36074U, t.Scan.Areas[6].Crc);
            Assert.Equal(0x5cc36074U, t.Scan.Areas[6].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[6].Size);
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.Equal("11", t.Scan.Areas[7].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000000.app", t.Scan.Areas[7].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[7].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[7].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal(AreaType.FstBlock, t.Scan.Areas[7].Type);
            Assert.Equal(0xeb9679b7U, t.Scan.Areas[7].Crc);
            Assert.Equal(0x5331b4caU, t.Scan.Areas[7].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[7].Size);
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[8].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000001.app", t.Scan.Areas[8].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[8].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[8].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[8].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[8].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[8].Type);
            Assert.Equal(0x2f443395U, t.Scan.Areas[8].Crc);
            Assert.Equal(0x2689bd77U, t.Scan.Areas[8].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[8].Size);
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[9].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000002.app", t.Scan.Areas[9].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[9].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[9].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[9].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[9].Type);
            Assert.Equal(0x2f443395U, t.Scan.Areas[9].Crc);
            Assert.Equal(0x2689bd77U, t.Scan.Areas[9].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[9].Size);
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[10].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[10].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000003.app", t.Scan.Areas[10].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[10].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[10].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[10].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[10].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[10].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[10].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[10].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[10].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[10].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[10].Type);
            Assert.Equal(0x2f443395U, t.Scan.Areas[10].Crc);
            Assert.Equal(0x2689bd77U, t.Scan.Areas[10].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[10].Size);
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[11].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("4", t.Scan.Areas[11].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000004.app", t.Scan.Areas[11].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[11].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[11].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[11].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[11].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[11].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[11].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[11].Type);
            Assert.Equal(0xd0990eceU, t.Scan.Areas[11].Crc);
            Assert.Equal(0xec73be24U, t.Scan.Areas[11].CrcDecrypted);
            Assert.Equal(0xb30000L, t.Scan.Areas[11].Size);
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[12].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("5", t.Scan.Areas[12].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000005.app", t.Scan.Areas[12].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[12].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[12].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[12].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[12].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[12].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[12].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[12].Type);
            Assert.Equal(0x2f443395U, t.Scan.Areas[12].Crc);
            Assert.Equal(0x2689bd77U, t.Scan.Areas[12].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[12].Size);
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[13].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("6", t.Scan.Areas[13].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000006.app", t.Scan.Areas[13].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[13].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[13].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[13].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[13].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[13].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[13].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[13].Type);
            Assert.Equal(0x2f443395U, t.Scan.Areas[13].Crc);
            Assert.Equal(0x2689bd77U, t.Scan.Areas[13].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[13].Size);
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[14].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("7", t.Scan.Areas[14].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000007.app", t.Scan.Areas[14].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[14].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[14].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[14].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[14].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[14].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[14].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[14].Type);
            Assert.Equal(0x715ecc8bU, t.Scan.Areas[14].Crc);
            Assert.Equal(0xd05bb5acU, t.Scan.Areas[14].CrcDecrypted);
            Assert.Equal(0x2090000L, t.Scan.Areas[14].Size);
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[15].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[15].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000008.app", t.Scan.Areas[15].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[15].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[15].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[15].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[15].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[15].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[15].Type);
            Assert.Equal(0xd9900d16U, t.Scan.Areas[15].Crc);
            Assert.Equal(0xd6ddbe3bU, t.Scan.Areas[15].CrcDecrypted);
            Assert.Equal(0x18000L, t.Scan.Areas[15].Size);
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[16].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("9", t.Scan.Areas[16].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000009.app", t.Scan.Areas[16].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[16].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[16].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[16].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[16].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[16].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[16].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[16].Type);
            Assert.Equal(0x2e2de1b4U, t.Scan.Areas[16].Crc);
            Assert.Equal(0xe209b931U, t.Scan.Areas[16].CrcDecrypted);
            Assert.Equal(0x7050000L, t.Scan.Areas[16].Size);
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[17].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[17].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("0000000a.app", t.Scan.Areas[17].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[17].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[17].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[17].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[17].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[17].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[17].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[17].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[17].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[17].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[17].Type);
            Assert.Equal(0x499dd9b3U, t.Scan.Areas[17].Crc);
            Assert.Equal(0x65c55e4cU, t.Scan.Areas[17].CrcDecrypted);
            Assert.Equal(0x1fb60000L, t.Scan.Areas[17].Size);
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[18].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[18].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[18].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[18].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[18].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[18].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[18].Type);
            Assert.Equal(0x5b01bc00U, t.Scan.Areas[18].Crc);
            Assert.Equal(0xa3514196U, t.Scan.Areas[18].CrcDecrypted);
            Assert.Equal(0x4e9d18000L, t.Scan.Areas[18].Size);

            base.Complete();
        }
    }
}