
using Nanook.NKit;
using System;
using System.IO;
using Xunit;

namespace NKit.Tests.Full.Wiped
{
    public partial class WipedImage_WiiU_Tests : WipedImageTestsBase
    {
        //Retail     / WUX       / 23.4GiB / Game Partition
        [Fact]
        public void Pbpbgb_Zntvp_Pvephf_7_Rhebcr_Ra_Se_Qr_Rf_Vg_Ay_Cg_wux_ConvertWux()
        {
            string fileName = @"Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux";
            string inPath = Path.GetFullPath(Path.Combine(@"../../../../../WipedImages", "WiiU"));
            string outFolderName = $"WiiU_Pbpbgb_Zntvp_Pvephf_7_Rhebcr_Ra_Se_Qr_Rf_Vg_Ay_Cg_wux_ConvertWux_{Guid.NewGuid():N}";
            string basePath = Directory.CreateDirectory(Path.Combine(".", outFolderName)).FullName;
            string dats = @"";
            string keys = @"../../../../../WipedImages/_keys";
            string fixInfo = @"";
            string fixFiles = @"";

            SystemPresetSettings presets = base.CreatePresets("Convert", @"wux", inPath, fileName, outFolderName, dats, keys, fixInfo, fixFiles);
            presets.System = SystemType.WiiU;

            NKitTaskResults t = base.ProcessImage(presets);
            NKitStepResult r = t.StepResults[0].Result;
            SourceFile f = t.Source;
            IStepInfo i = r.StepInfo;
            Scan s = t.Scan;

            ////////////////////////////////////////
            // Source File
            ////////////////////////////////////////
            Assert.NotNull(f);
            Assert.Equal(inPath.TrimEnd('\\', '/'), f.BasePath.TrimEnd('\\', '/'));
            Assert.NotNull(f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux", f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg)", f.CleanName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg)", f.Name);
            Assert.Equal(SourceImageType.Wux, f.ImageType);
            Assert.Equal(SourceFileResult.Valid, f.Status);
            Assert.Equal(SystemType.WiiU, f.SystemType);
            Assert.False(f.IsArchive);
            Assert.False(f.IsArchived);
            Assert.False(f.IsDeleted);
            Assert.False(f.IsFolderMode);
            Assert.False(f.IsSplitArchive);
            Assert.False(f.IsSplitImage);
            Assert.Equal(0x0L, f.Length);
            Assert.Equal(1, f.ImageFiles.Length);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux", f.ImageFiles[0].FileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg)", f.ImageFiles[0].NameOnly);
            Assert.Equal(".wux", f.ImageFiles[0].Extension);
            Assert.Equal(0x74d0000L, f.ImageFiles[0].Size);
            Assert.False(f.ImageFiles[0].IsArchived);
            Assert.Equal(SourceArchiveType.None, f.ArchiveType);
            Assert.Null(f.ArchiveFiles);
            Assert.NotNull(f.Key);
            Assert.Equal("F0F1F2F3F4F5F6F7F8F9FAFBFCFDFEFF", f.Key.ToHexString());
            // f.IndexFile IndexFile Test
            Assert.Null(f.IndexFile);

            ////////////////////////////////////////
            // Step Info
            ////////////////////////////////////////
            Assert.NotNull(i);
            Assert.False(i.CanCrc);
            Assert.False(i.CanHash);
            Assert.False(i.CreateInChecksum);
            Assert.False(i.CreateOutChecksum);
            Assert.True(i.CreateScan);
            Assert.False(i.DeleteSourceCandidate);
            Assert.True(i.FullScan);
            Assert.False(i.IsExpand);
            Assert.False(i.IsFix);
            Assert.False(i.IsLossy);
            Assert.True(i.WriteImage);
            Assert.Equal("Convert-WiiU-Wux", i.Name);
            Assert.Equal(OutputType.Image, i.OutputType);
            Assert.False(i.ReqChk);
            Assert.False(i.ReqPatch);
            Assert.Equal(TaskType.Convert, i.StepType);
            Assert.Equal(VerifyMethod.NoVerify, i.VerifyMethod);
            Assert.Null(i.VerifyChecksums);
            Assert.NotNull(i.Config);
            Assert.Equal("wux", i.Config);
            Assert.NotNull(i.ImageConfig);
            Assert.Equal("wux", i.ImageConfig);
            Assert.NotNull(i.SrcParts);
            Assert.Equal(1, i.SrcParts.Length);
            Assert.Equal(0x0L, i.SrcParts[0].Size);
            Assert.NotNull(i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Equal("", i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Null(i.SrcParts[0].FileName);

            ////////////////////////////////////////
            // Source Scan
            ////////////////////////////////////////
            Assert.Null(i.SrcScan);

            ////////////////////////////////////////
            // Source DatItem
            ////////////////////////////////////////
            Assert.Null(i.DatMatch);

            ////////////////////////////////////////
            // Step Result
            ////////////////////////////////////////
            Assert.NotNull(r);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux", r.FinalName);
            Assert.Null(r.ChkCompared);
            Assert.Null(r.InFileParts);
            Assert.NotNull(r.OutFileParts);
            Assert.Equal(1, r.OutFileParts.Length);
            Assert.Equal(0x74d0000L, r.OutFileParts[0].Size);
            Assert.NotNull(r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:881A84E5", r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.NotNull(r.OutFileParts[0].FileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux~", r.OutFileParts[0].FileName);
            Assert.NotNull(r.ResultCrc);
            Assert.Equal(0xd09aa38bU, r.ResultCrc.Value);
            Assert.NotNull(r.ResultSize);
            Assert.Equal(0x5d3a00000L, r.ResultSize.Value);
            Assert.NotNull(r.Scan);
            Assert.NotNull(r.StepInfo);
            Assert.Equal(VerifyResult.Unverified, r.VerifyResult);
            Assert.Equal("NoVerify", r.VerifyType);

            ////////////////////////////////////////
            // StepResult DatItem
            ////////////////////////////////////////
            Assert.Null(r.MatchedDatItem);

            ////////////////////////////////////////
            // Task Result
            ////////////////////////////////////////
            Assert.Equal(ContainerType.Wux, t.ContainerType);
            Assert.Equal(SystemType.WiiU, t.System);
            Assert.Equal(TaskType.Convert, t.Task);
            Assert.Equal(0x5d3a00000L, t.Size);
            Assert.Equal(0xd09aa38bU, t.CRC);
            Assert.Equal(0x7de4d9f8U, t.DecryptedCrc);
            Assert.Equal(VerifyResult.Unverified, t.VerifyResult);
            Assert.Equal(inPath.TrimEnd('\\', '/'), t.InFilePath.TrimEnd('\\', '/'));
            Assert.Equal(basePath.TrimEnd('\\', '/'), t.OutPath.TrimEnd('\\', '/'));
            Assert.NotNull(t.Name);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg)", t.Name);
            Assert.NotNull(t.VerifyType);
            Assert.Equal("NoVerify", t.VerifyType);
            Assert.NotNull(t.VerifyChecksum);
            Assert.Equal("", t.VerifyChecksum);
            Assert.Null(t.DatMatch);
            Assert.Null(t.ErrorMsg);
            Assert.NotNull(t.OutFileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux", t.OutFileName);
            Assert.Null(t.OutKeyFilePath);
            Assert.NotNull(t.OutScanFilePath);
            Assert.Equal(Path.Combine(basePath, "Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).nkit.yaml"), t.OutScanFilePath);
            Assert.True(t.HasEncryption);
            Assert.True(t.SupportsEncryption);
            Assert.False(t.ImageSkipped);
            Assert.NotNull(t.Key);
            Assert.Equal("F0F1F2F3F4F5F6F7F8F9FAFBFCFDFEFF", t.Key.ToHexString());
            Assert.NotNull(t.StepFiles);
            Assert.Equal(1, t.StepFiles.Count);
            Assert.Equal(0x74d0000L, t.StepFiles[0].Size);
            Assert.False(t.StepFiles[0].IsIndex);
            Assert.True(t.StepFiles[0].IsImageName);
            Assert.NotNull(t.StepFiles[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:881A84E5", t.StepFiles[0].Checksums.ToString(true, true));
            Assert.NotNull(t.StepFiles[0].FileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg).wux~", t.StepFiles[0].FileName);

            ////////////////////////////////////////
            // Result Scan
            ////////////////////////////////////////
            Assert.NotNull(t.Scan);
            Assert.NotNull(t.Scan.Name);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg)", t.Scan.Name);
            Assert.Equal(SystemType.WiiU, f.SystemType);
            Assert.Equal(0xd09aa38bU, t.Scan.Crc);
            Assert.Equal(0x7de4d9f8U, t.Scan.CrcDecrypted);
            Assert.Equal(0x5d3a00000L, t.Scan.Size);
            Assert.Equal(6916, t.Scan.VirtualFsTotalFileCount);
            Assert.Equal(902, t.Scan.VirtualFsTotalFoldersCount);
            Assert.NotNull(t.Scan.Properties["System"].ToXmlValue());
            Assert.Equal("WiiU", t.Scan.Properties["System"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Media"].ToXmlValue());
            Assert.Equal("WUD", t.Scan.Properties["Media"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Type"].ToXmlValue());
            Assert.Equal("Retail", t.Scan.Properties["Type"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Size"].ToXmlValue());
            Assert.Equal("5D3A00000", t.Scan.Properties["Size"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["CRC"].ToXmlValue());
            Assert.Equal("D09AA38B", t.Scan.Properties["CRC"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal("7DE4D9F8", t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal(22, t.Scan.Areas.Count);
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("WUP-C-NPPC-55-656RHE-7", t.Scan.Areas[0].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal(AreaType.ImageHeader, t.Scan.Areas[0].Type);
            Assert.Equal(0x5c33bfb0U, t.Scan.Areas[0].Crc);
            Assert.Equal(0x5c33bfb0U, t.Scan.Areas[0].CrcDecrypted);
            Assert.Equal(0x18000L, t.Scan.Areas[0].Size);
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Partitions"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[1].AreaInfo.Properties["Partitions"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[1].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["KeyCrc"].ToXmlValue());
            Assert.Equal("61E8443C", t.Scan.Areas[1].AreaInfo.Properties["KeyCrc"].ToXmlValue());
            Assert.Equal(AreaType.PartitionTable, t.Scan.Areas[1].Type);
            Assert.Equal(0x79b9312bU, t.Scan.Areas[1].Crc);
            Assert.Equal(0xb4c1bf33U, t.Scan.Areas[1].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[1].Size);
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Si", t.Scan.Areas[2].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.Equal("SI", t.Scan.Areas[2].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("0000000000000000", t.Scan.Areas[2].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[2].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[2].Type);
            Assert.Equal(0x1e89374eU, t.Scan.Areas[2].Crc);
            Assert.Equal(0x1e89374eU, t.Scan.Areas[2].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[2].Size);
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[3].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[3].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[3].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal(AreaType.FstBlock, t.Scan.Areas[3].Type);
            Assert.Equal(0x69f6773dU, t.Scan.Areas[3].Crc);
            Assert.Equal(0x77ccd43cU, t.Scan.Areas[3].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[3].Size);
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[4].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[4].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[4].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[4].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("555055556567A555", t.Scan.Areas[4].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[4].Type);
            Assert.Equal(0x0e76b07fU, t.Scan.Areas[4].Crc);
            Assert.Equal(0x8ed8dfceU, t.Scan.Areas[4].CrcDecrypted);
            Assert.Equal(0x400000L, t.Scan.Areas[4].Size);
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[5].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[5].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[5].Type);
            Assert.Equal(0xd87ffabfU, t.Scan.Areas[5].Crc);
            Assert.Equal(0xe39aea2fU, t.Scan.Areas[5].CrcDecrypted);
            Assert.Equal(0x3fbd0000L, t.Scan.Areas[5].Size);
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Update", t.Scan.Areas[6].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.Equal("UP0000000000000000000000000000", t.Scan.Areas[6].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("0000000000000000", t.Scan.Areas[6].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[6].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[6].Type);
            Assert.Equal(0x0c6b5c08U, t.Scan.Areas[6].Crc);
            Assert.Equal(0x0c6b5c08U, t.Scan.Areas[6].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[6].Size);
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[7].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[7].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal(AreaType.FstBlock, t.Scan.Areas[7].Type);
            Assert.Equal(0x59ca6550U, t.Scan.Areas[7].Crc);
            Assert.Equal(0x5d7430e2U, t.Scan.Areas[7].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[7].Size);
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[8].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[8].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[8].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[8].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[8].Type);
            Assert.Equal(0x9d0cdd55U, t.Scan.Areas[8].Crc);
            Assert.Equal(0x25d5e580U, t.Scan.Areas[8].CrcDecrypted);
            Assert.Equal(0x6a28000L, t.Scan.Areas[8].Size);
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[9].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[9].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[9].Type);
            Assert.Equal(0x842e807bU, t.Scan.Areas[9].Crc);
            Assert.Equal(0xae6223e9U, t.Scan.Areas[9].CrcDecrypted);
            Assert.Equal(0x795c8000L, t.Scan.Areas[9].Size);
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[10].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Game", t.Scan.Areas[10].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.Equal("GM555055556567A555555555555555", t.Scan.Areas[10].AreaInfo.Properties["VolumeId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("555055556567A555", t.Scan.Areas[10].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[10].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[10].Type);
            Assert.Equal(0xc7bf8354U, t.Scan.Areas[10].Crc);
            Assert.Equal(0xc7bf8354U, t.Scan.Areas[10].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[10].Size);
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[11].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[11].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000000.app", t.Scan.Areas[11].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[11].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[11].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[11].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal(AreaType.FstBlock, t.Scan.Areas[11].Type);
            Assert.Equal(0x3fdfa402U, t.Scan.Areas[11].Crc);
            Assert.Equal(0x846ae335U, t.Scan.Areas[11].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[11].Size);
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[12].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[12].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000001.app", t.Scan.Areas[12].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[12].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[12].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[12].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[12].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[12].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[12].Type);
            Assert.Equal(0x9ed15493U, t.Scan.Areas[12].Crc);
            Assert.Equal(0xe6c84bffU, t.Scan.Areas[12].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[12].Size);
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[13].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[13].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000002.app", t.Scan.Areas[13].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[13].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[13].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[13].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[13].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[13].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[13].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[13].Type);
            Assert.Equal(0x0e8c2163U, t.Scan.Areas[13].Crc);
            Assert.Equal(0xec64602bU, t.Scan.Areas[13].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[13].Size);
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[14].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[14].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000003.app", t.Scan.Areas[14].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[14].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[14].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[14].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[14].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[14].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[14].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[14].Type);
            Assert.Equal(0x83fc5099U, t.Scan.Areas[14].Crc);
            Assert.Equal(0x4af3f8e5U, t.Scan.Areas[14].CrcDecrypted);
            Assert.Equal(0x30000L, t.Scan.Areas[14].Size);
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[15].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("4", t.Scan.Areas[15].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000004.app", t.Scan.Areas[15].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[15].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[15].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[15].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[15].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[15].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[15].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[15].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[15].Type);
            Assert.Equal(0x8a39f52aU, t.Scan.Areas[15].Crc);
            Assert.Equal(0xbdfcfba8U, t.Scan.Areas[15].CrcDecrypted);
            Assert.Equal(0xb30000L, t.Scan.Areas[15].Size);
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[16].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("5", t.Scan.Areas[16].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000005.app", t.Scan.Areas[16].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[16].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[16].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[16].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[16].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[16].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[16].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[16].Type);
            Assert.Equal(0xc5c9dfd6U, t.Scan.Areas[16].Crc);
            Assert.Equal(0xef90ac5eU, t.Scan.Areas[16].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[16].Size);
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[17].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("6", t.Scan.Areas[17].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000006.app", t.Scan.Areas[17].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[17].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[17].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[17].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[17].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[17].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[17].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[17].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[17].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[17].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[17].Type);
            Assert.Equal(0x710b706eU, t.Scan.Areas[17].Crc);
            Assert.Equal(0xfbafc37eU, t.Scan.Areas[17].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[17].Size);
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[18].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("7", t.Scan.Areas[18].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000007.app", t.Scan.Areas[18].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[18].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[18].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[18].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[18].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[18].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[18].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[18].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[18].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[18].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[18].Type);
            Assert.Equal(0x111e5dbaU, t.Scan.Areas[18].Crc);
            Assert.Equal(0xa761359bU, t.Scan.Areas[18].CrcDecrypted);
            Assert.Equal(0x2090000L, t.Scan.Areas[18].Size);
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[19].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[19].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000008.app", t.Scan.Areas[19].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[19].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[19].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[19].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[19].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[19].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[19].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[19].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[19].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[19].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[19].Type);
            Assert.Equal(0xba219738U, t.Scan.Areas[19].Crc);
            Assert.Equal(0xe3d34cf4U, t.Scan.Areas[19].CrcDecrypted);
            Assert.Equal(0x2a0000L, t.Scan.Areas[19].Size);
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[20].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[20].AreaInfo.Properties["RepeatedContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[20].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.Equal("false", t.Scan.Areas[20].AreaInfo.Properties["Hashes"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[20].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[20].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[20].Type);
            Assert.Equal(0x5ef0ccb8U, t.Scan.Areas[20].Crc);
            Assert.Equal(0x98e81e9cU, t.Scan.Areas[20].CrcDecrypted);
            Assert.Equal(0x4fca20000L, t.Scan.Areas[20].Size);
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[21].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("9", t.Scan.Areas[21].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000009.app", t.Scan.Areas[21].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[21].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[21].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[21].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[21].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[21].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[21].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[21].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[21].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[21].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[21].Type);
            Assert.Equal(0x6a47a018U, t.Scan.Areas[21].Crc);
            Assert.Equal(0xe5b03249U, t.Scan.Areas[21].CrcDecrypted);
            Assert.Equal(0x13f10000L, t.Scan.Areas[21].Size);

            base.Complete();
        }
    }
}