
using Nanook.NKit;
using System;
using System.IO;
using Xunit;

namespace NKit.Tests.Full.Wiped
{
    public partial class WipedImage_WiiU_Tests : WipedImageTestsBase
    {
        //Retail     / APP       / 367MiB  / App with tmd, tik, cert and H3 files
        [Fact]
        public void Pbpbgb_Zntvp_Pvephf_7_Rhebcr_Ra_Se_Qr_Rf_Vg_Ay_Cg_555055556567Q555_7z_Scan()
        {
            string fileName = @"Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555].7z";
            string inPath = Path.GetFullPath(Path.Combine(@"../../../../../WipedImages", "WiiU"));
            string outFolderName = $"WiiU_Pbpbgb_Zntvp_Pvephf_7_Rhebcr_Ra_Se_Qr_Rf_Vg_Ay_Cg_555055556567Q555_7z_Scan_{Guid.NewGuid():N}";
            string basePath = Directory.CreateDirectory(Path.Combine(".", outFolderName)).FullName;
            string dats = @"";
            string keys = @"../../../../../WipedImages/_keys";
            string fixInfo = @"";
            string fixFiles = @"";

            SystemPresetSettings presets = base.CreatePresets("Scan", @"", inPath, fileName, outFolderName, dats, keys, fixInfo, fixFiles);
            presets.System = SystemType.WiiU;

            NKitTaskResults t = base.ProcessImage(presets);
            NKitStepResult r = t.StepResults[0].Result;
            SourceFile f = t.Source;
            IStepInfo i = r.StepInfo;
            Scan s = t.Scan;

            ////////////////////////////////////////
            // Source File
            ////////////////////////////////////////
            Assert.NotNull(f);
            Assert.Equal(inPath.TrimEnd('\\', '/'), f.BasePath.TrimEnd('\\', '/'));
            Assert.NotNull(f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555].7z//title.tmd +10", f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", f.CleanName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", f.Name);
            Assert.Equal(SourceImageType.TmdApp, f.ImageType);
            Assert.Equal(SourceFileResult.Valid, f.Status);
            Assert.Equal(SystemType.WiiU, f.SystemType);
            Assert.False(f.IsArchive);
            Assert.True(f.IsArchived);
            Assert.False(f.IsDeleted);
            Assert.True(f.IsFolderMode);
            Assert.False(f.IsSplitArchive);
            Assert.True(f.IsSplitImage);
            Assert.Equal(0x0L, f.Length);
            Assert.Equal(10, f.ImageFiles.Length);
            Assert.Equal("00000000.app", f.ImageFiles[0].FileName);
            Assert.Equal("00000000", f.ImageFiles[0].NameOnly);
            Assert.Equal(".app", f.ImageFiles[0].Extension);
            Assert.Equal(0x8000L, f.ImageFiles[0].Size);
            Assert.True(f.ImageFiles[0].IsArchived);
            Assert.Equal("00000001.app", f.ImageFiles[1].FileName);
            Assert.Equal("00000001", f.ImageFiles[1].NameOnly);
            Assert.Equal(".app", f.ImageFiles[1].Extension);
            Assert.Equal(0x8000L, f.ImageFiles[1].Size);
            Assert.True(f.ImageFiles[1].IsArchived);
            Assert.Equal("00000002.app", f.ImageFiles[2].FileName);
            Assert.Equal("00000002", f.ImageFiles[2].NameOnly);
            Assert.Equal(".app", f.ImageFiles[2].Extension);
            Assert.Equal(0x8000L, f.ImageFiles[2].Size);
            Assert.True(f.ImageFiles[2].IsArchived);
            Assert.Equal("00000003.app", f.ImageFiles[3].FileName);
            Assert.Equal("00000003", f.ImageFiles[3].NameOnly);
            Assert.Equal(".app", f.ImageFiles[3].Extension);
            Assert.Equal(0x30000L, f.ImageFiles[3].Size);
            Assert.True(f.ImageFiles[3].IsArchived);
            Assert.Equal("00000004.app", f.ImageFiles[4].FileName);
            Assert.Equal("00000004", f.ImageFiles[4].NameOnly);
            Assert.Equal(".app", f.ImageFiles[4].Extension);
            Assert.Equal(0xb30000L, f.ImageFiles[4].Size);
            Assert.True(f.ImageFiles[4].IsArchived);
            Assert.Equal("00000005.app", f.ImageFiles[5].FileName);
            Assert.Equal("00000005", f.ImageFiles[5].NameOnly);
            Assert.Equal(".app", f.ImageFiles[5].Extension);
            Assert.Equal(0x110000L, f.ImageFiles[5].Size);
            Assert.True(f.ImageFiles[5].IsArchived);
            Assert.Equal("00000006.app", f.ImageFiles[6].FileName);
            Assert.Equal("00000006", f.ImageFiles[6].NameOnly);
            Assert.Equal(".app", f.ImageFiles[6].Extension);
            Assert.Equal(0x110000L, f.ImageFiles[6].Size);
            Assert.True(f.ImageFiles[6].IsArchived);
            Assert.Equal("00000007.app", f.ImageFiles[7].FileName);
            Assert.Equal("00000007", f.ImageFiles[7].NameOnly);
            Assert.Equal(".app", f.ImageFiles[7].Extension);
            Assert.Equal(0x2090000L, f.ImageFiles[7].Size);
            Assert.True(f.ImageFiles[7].IsArchived);
            Assert.Equal("00000008.app", f.ImageFiles[8].FileName);
            Assert.Equal("00000008", f.ImageFiles[8].NameOnly);
            Assert.Equal(".app", f.ImageFiles[8].Extension);
            Assert.Equal(0x2a0000L, f.ImageFiles[8].Size);
            Assert.True(f.ImageFiles[8].IsArchived);
            Assert.Equal("00000009.app", f.ImageFiles[9].FileName);
            Assert.Equal("00000009", f.ImageFiles[9].NameOnly);
            Assert.Equal(".app", f.ImageFiles[9].Extension);
            Assert.Equal(0x13f10000L, f.ImageFiles[9].Size);
            Assert.True(f.ImageFiles[9].IsArchived);
            Assert.Equal(SourceArchiveType.SevenZip, f.ArchiveType);
            Assert.NotNull(f.ArchiveFiles);
            Assert.Equal(1, f.ArchiveFiles.Length);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555].7z", f.ArchiveFiles[0].FileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", f.ArchiveFiles[0].NameOnly);
            Assert.Equal(".7z", f.ArchiveFiles[0].Extension);
            Assert.Equal(0x3383fcL, f.ArchiveFiles[0].Size);
            Assert.False(f.ArchiveFiles[0].IsArchived);
            Assert.NotNull(f.Key);
            Assert.Equal("75B928E955968EB352E6B19A9B2E4EBE", f.Key.ToHexString());
            // f.IndexFile IndexFile Test
            Assert.NotNull(f.IndexFile);
            Assert.Equal(0x8458adfbU, f.IndexFile.Crc);
            Assert.Equal(IndexFileType.TmdApp, f.IndexFile.FileType);
            Assert.False(f.IndexFile.IsArchived);
            Assert.False(f.IndexFile.IsTemp);
            Assert.Equal(0x0L, f.IndexFile.Offset);
            Assert.Equal(0xce4L, f.IndexFile.Size);
            Assert.False(f.IndexFile.WiiUFstMismatch);
            Assert.NotNull(f.IndexFile.Extension);
            Assert.Equal(".tmd", f.IndexFile.Extension);
            Assert.NotNull(f.IndexFile.FileName);
            Assert.Equal("title.tmd", f.IndexFile.FileName);
            Assert.NotNull(f.IndexFile.NameOnly);
            Assert.Equal("title", f.IndexFile.NameOnly);
            Assert.NotNull(f.IndexFile.Postfix);
            Assert.Equal(".tmd", f.IndexFile.Postfix);
            Assert.NotNull(f.IndexFile.Path);
            Assert.Equal("", f.IndexFile.Path);
            Assert.Equal(10, f.IndexFile.Items.Length);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[0].BasicType);
            Assert.Equal(0, f.IndexFile.Items[0].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[0].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[0].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[0].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[0].ChdSubType);
            Assert.False(f.IndexFile.Items[0].FileIsMissing);
            Assert.Equal(0x0L, f.IndexFile.Items[0].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[0].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[0].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[0].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[0].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[0].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[0].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[0].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[0].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[0].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[0].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[0].Session);
            Assert.Equal(0x8000L, f.IndexFile.Items[0].Size);
            Assert.Equal(0x0, f.IndexFile.Items[0].SubSize);
            Assert.Equal(0, f.IndexFile.Items[0].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[0].TrackType);
            Assert.Null(f.IndexFile.Items[0].ChdTag);
            Assert.Null(f.IndexFile.Items[0].Comment);
            Assert.NotNull(f.IndexFile.Items[0].FileName);
            Assert.Equal("00000000.app", f.IndexFile.Items[0].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[1].BasicType);
            Assert.Equal(0, f.IndexFile.Items[1].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[1].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[1].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[1].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[1].ChdSubType);
            Assert.False(f.IndexFile.Items[1].FileIsMissing);
            Assert.Equal(0x8000L, f.IndexFile.Items[1].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[1].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[1].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[1].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[1].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[1].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[1].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[1].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[1].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[1].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[1].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[1].Session);
            Assert.Equal(0x8000L, f.IndexFile.Items[1].Size);
            Assert.Equal(0x0, f.IndexFile.Items[1].SubSize);
            Assert.Equal(1, f.IndexFile.Items[1].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[1].TrackType);
            Assert.Null(f.IndexFile.Items[1].ChdTag);
            Assert.Null(f.IndexFile.Items[1].Comment);
            Assert.NotNull(f.IndexFile.Items[1].FileName);
            Assert.Equal("00000001.app", f.IndexFile.Items[1].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[2].BasicType);
            Assert.Equal(0, f.IndexFile.Items[2].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[2].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[2].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[2].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[2].ChdSubType);
            Assert.False(f.IndexFile.Items[2].FileIsMissing);
            Assert.Equal(0x10000L, f.IndexFile.Items[2].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[2].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[2].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[2].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[2].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[2].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[2].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[2].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[2].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[2].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[2].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[2].Session);
            Assert.Equal(0x8000L, f.IndexFile.Items[2].Size);
            Assert.Equal(0x0, f.IndexFile.Items[2].SubSize);
            Assert.Equal(2, f.IndexFile.Items[2].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[2].TrackType);
            Assert.Null(f.IndexFile.Items[2].ChdTag);
            Assert.Null(f.IndexFile.Items[2].Comment);
            Assert.NotNull(f.IndexFile.Items[2].FileName);
            Assert.Equal("00000002.app", f.IndexFile.Items[2].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[3].BasicType);
            Assert.Equal(0, f.IndexFile.Items[3].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[3].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[3].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[3].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[3].ChdSubType);
            Assert.False(f.IndexFile.Items[3].FileIsMissing);
            Assert.Equal(0x18000L, f.IndexFile.Items[3].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[3].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[3].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[3].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[3].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[3].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[3].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[3].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[3].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[3].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[3].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[3].Session);
            Assert.Equal(0x30000L, f.IndexFile.Items[3].Size);
            Assert.Equal(0x0, f.IndexFile.Items[3].SubSize);
            Assert.Equal(3, f.IndexFile.Items[3].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[3].TrackType);
            Assert.Null(f.IndexFile.Items[3].ChdTag);
            Assert.Null(f.IndexFile.Items[3].Comment);
            Assert.NotNull(f.IndexFile.Items[3].FileName);
            Assert.Equal("00000003.app", f.IndexFile.Items[3].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[4].BasicType);
            Assert.Equal(0, f.IndexFile.Items[4].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[4].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[4].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[4].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[4].ChdSubType);
            Assert.False(f.IndexFile.Items[4].FileIsMissing);
            Assert.Equal(0x48000L, f.IndexFile.Items[4].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[4].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[4].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[4].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[4].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[4].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[4].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[4].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[4].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[4].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[4].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[4].Session);
            Assert.Equal(0xb30000L, f.IndexFile.Items[4].Size);
            Assert.Equal(0x0, f.IndexFile.Items[4].SubSize);
            Assert.Equal(4, f.IndexFile.Items[4].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[4].TrackType);
            Assert.Null(f.IndexFile.Items[4].ChdTag);
            Assert.Null(f.IndexFile.Items[4].Comment);
            Assert.NotNull(f.IndexFile.Items[4].FileName);
            Assert.Equal("00000004.app", f.IndexFile.Items[4].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[5].BasicType);
            Assert.Equal(0, f.IndexFile.Items[5].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[5].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[5].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[5].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[5].ChdSubType);
            Assert.False(f.IndexFile.Items[5].FileIsMissing);
            Assert.Equal(0xb78000L, f.IndexFile.Items[5].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[5].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[5].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[5].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[5].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[5].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[5].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[5].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[5].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[5].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[5].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[5].Session);
            Assert.Equal(0x110000L, f.IndexFile.Items[5].Size);
            Assert.Equal(0x0, f.IndexFile.Items[5].SubSize);
            Assert.Equal(5, f.IndexFile.Items[5].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[5].TrackType);
            Assert.Null(f.IndexFile.Items[5].ChdTag);
            Assert.Null(f.IndexFile.Items[5].Comment);
            Assert.NotNull(f.IndexFile.Items[5].FileName);
            Assert.Equal("00000005.app", f.IndexFile.Items[5].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[6].BasicType);
            Assert.Equal(0, f.IndexFile.Items[6].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[6].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[6].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[6].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[6].ChdSubType);
            Assert.False(f.IndexFile.Items[6].FileIsMissing);
            Assert.Equal(0xc88000L, f.IndexFile.Items[6].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[6].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[6].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[6].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[6].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[6].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[6].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[6].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[6].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[6].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[6].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[6].Session);
            Assert.Equal(0x110000L, f.IndexFile.Items[6].Size);
            Assert.Equal(0x0, f.IndexFile.Items[6].SubSize);
            Assert.Equal(6, f.IndexFile.Items[6].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[6].TrackType);
            Assert.Null(f.IndexFile.Items[6].ChdTag);
            Assert.Null(f.IndexFile.Items[6].Comment);
            Assert.NotNull(f.IndexFile.Items[6].FileName);
            Assert.Equal("00000006.app", f.IndexFile.Items[6].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[7].BasicType);
            Assert.Equal(0, f.IndexFile.Items[7].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[7].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[7].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[7].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[7].ChdSubType);
            Assert.False(f.IndexFile.Items[7].FileIsMissing);
            Assert.Equal(0xd98000L, f.IndexFile.Items[7].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[7].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[7].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[7].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[7].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[7].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[7].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[7].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[7].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[7].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[7].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[7].Session);
            Assert.Equal(0x2090000L, f.IndexFile.Items[7].Size);
            Assert.Equal(0x0, f.IndexFile.Items[7].SubSize);
            Assert.Equal(7, f.IndexFile.Items[7].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[7].TrackType);
            Assert.Null(f.IndexFile.Items[7].ChdTag);
            Assert.Null(f.IndexFile.Items[7].Comment);
            Assert.NotNull(f.IndexFile.Items[7].FileName);
            Assert.Equal("00000007.app", f.IndexFile.Items[7].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[8].BasicType);
            Assert.Equal(0, f.IndexFile.Items[8].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[8].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[8].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[8].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[8].ChdSubType);
            Assert.False(f.IndexFile.Items[8].FileIsMissing);
            Assert.Equal(0x2e28000L, f.IndexFile.Items[8].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[8].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[8].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[8].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[8].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[8].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[8].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[8].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[8].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[8].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[8].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[8].Session);
            Assert.Equal(0x2a0000L, f.IndexFile.Items[8].Size);
            Assert.Equal(0x0, f.IndexFile.Items[8].SubSize);
            Assert.Equal(8, f.IndexFile.Items[8].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[8].TrackType);
            Assert.Null(f.IndexFile.Items[8].ChdTag);
            Assert.Null(f.IndexFile.Items[8].Comment);
            Assert.NotNull(f.IndexFile.Items[8].FileName);
            Assert.Equal("00000008.app", f.IndexFile.Items[8].FileName);
            Assert.Equal(IndexTrackBasicType.Unknown, f.IndexFile.Items[9].BasicType);
            Assert.Equal(0, f.IndexFile.Items[9].BlockIdx);
            Assert.Equal(0x0, f.IndexFile.Items[9].BlockSize);
            Assert.Equal(0, f.IndexFile.Items[9].Blocks);
            Assert.Equal(MediaType.Unknown, f.IndexFile.Items[9].ChdMediaType);
            Assert.Equal(CdSubType.None, f.IndexFile.Items[9].ChdSubType);
            Assert.False(f.IndexFile.Items[9].FileIsMissing);
            Assert.Equal(0x30c8000L, f.IndexFile.Items[9].ImageOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[9].PhysicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[9].LogicalOffset);
            Assert.Equal(0x0L, f.IndexFile.Items[9].LogicalSize);
            Assert.Equal(0x0, f.IndexFile.Items[9].Pad);
            Assert.Equal(0x0, f.IndexFile.Items[9].PadSize);
            Assert.Equal(0x0, f.IndexFile.Items[9].PostGap);
            Assert.Equal(0x0, f.IndexFile.Items[9].PreGap);
            Assert.Equal(0x0, f.IndexFile.Items[9].PreGapDataSize);
            Assert.Equal(0x0, f.IndexFile.Items[9].PreGapSubSize);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[9].PreGapType);
            Assert.Equal(0, f.IndexFile.Items[9].Session);
            Assert.Equal(0x13f10000L, f.IndexFile.Items[9].Size);
            Assert.Equal(0x0, f.IndexFile.Items[9].SubSize);
            Assert.Equal(9, f.IndexFile.Items[9].TrackIndex);
            Assert.Equal(IndexTrackType.Unknown, f.IndexFile.Items[9].TrackType);
            Assert.Null(f.IndexFile.Items[9].ChdTag);
            Assert.Null(f.IndexFile.Items[9].Comment);
            Assert.NotNull(f.IndexFile.Items[9].FileName);
            Assert.Equal("00000009.app", f.IndexFile.Items[9].FileName);
            Assert.Equal(8, f.IndexFile.Additional.Count);
            Assert.Equal(0x14L, f.IndexFile.Additional[0].Size);
            Assert.NotNull(f.IndexFile.Additional[0].FileName);
            Assert.Equal("00000003.h3", f.IndexFile.Additional[0].FileName);
            Assert.Equal(0x14L, f.IndexFile.Additional[1].Size);
            Assert.NotNull(f.IndexFile.Additional[1].FileName);
            Assert.Equal("00000004.h3", f.IndexFile.Additional[1].FileName);
            Assert.Equal(0x14L, f.IndexFile.Additional[2].Size);
            Assert.NotNull(f.IndexFile.Additional[2].FileName);
            Assert.Equal("00000005.h3", f.IndexFile.Additional[2].FileName);
            Assert.Equal(0x14L, f.IndexFile.Additional[3].Size);
            Assert.NotNull(f.IndexFile.Additional[3].FileName);
            Assert.Equal("00000006.h3", f.IndexFile.Additional[3].FileName);
            Assert.Equal(0x14L, f.IndexFile.Additional[4].Size);
            Assert.NotNull(f.IndexFile.Additional[4].FileName);
            Assert.Equal("00000007.h3", f.IndexFile.Additional[4].FileName);
            Assert.Equal(0x28L, f.IndexFile.Additional[5].Size);
            Assert.NotNull(f.IndexFile.Additional[5].FileName);
            Assert.Equal("00000009.h3", f.IndexFile.Additional[5].FileName);
            Assert.Equal(0xa00L, f.IndexFile.Additional[6].Size);
            Assert.NotNull(f.IndexFile.Additional[6].FileName);
            Assert.Equal("title.cert", f.IndexFile.Additional[6].FileName);
            Assert.Equal(0x350L, f.IndexFile.Additional[7].Size);
            Assert.NotNull(f.IndexFile.Additional[7].FileName);
            Assert.Equal("title.tik", f.IndexFile.Additional[7].FileName);

            ////////////////////////////////////////
            // Step Info
            ////////////////////////////////////////
            Assert.NotNull(i);
            Assert.True(i.CanCrc);
            Assert.True(i.CanHash);
            Assert.False(i.CreateInChecksum);
            Assert.False(i.CreateOutChecksum);
            Assert.True(i.CreateScan);
            Assert.False(i.DeleteSourceCandidate);
            Assert.True(i.FullScan);
            Assert.True(i.IsExpand);
            Assert.False(i.IsFix);
            Assert.False(i.IsLossy);
            Assert.False(i.WriteImage);
            Assert.Equal("Scan-Image", i.Name);
            Assert.Equal(OutputType.Scan, i.OutputType);
            Assert.False(i.ReqChk);
            Assert.False(i.ReqPatch);
            Assert.Equal(TaskType.Scan, i.StepType);
            Assert.Equal(VerifyMethod.NoVerify, i.VerifyMethod);
            Assert.Null(i.VerifyChecksums);
            Assert.NotNull(i.Config);
            Assert.Equal("scan", i.Config);
            Assert.NotNull(i.ImageConfig);
            Assert.Equal("scan", i.ImageConfig);
            Assert.NotNull(i.SrcParts);
            Assert.Equal(1, i.SrcParts.Length);
            Assert.Equal(0x0L, i.SrcParts[0].Size);
            Assert.NotNull(i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Equal("", i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Null(i.SrcParts[0].FileName);

            ////////////////////////////////////////
            // Source Scan
            ////////////////////////////////////////
            Assert.Null(i.SrcScan);

            ////////////////////////////////////////
            // Source DatItem
            ////////////////////////////////////////
            Assert.Null(i.DatMatch);

            ////////////////////////////////////////
            // Step Result
            ////////////////////////////////////////
            Assert.NotNull(r);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555].nkit.yaml", r.FinalName);
            Assert.Null(r.ChkCompared);
            Assert.Null(r.InFileParts);
            Assert.NotNull(r.OutFileParts);
            Assert.Equal(1, r.OutFileParts.Length);
            Assert.Equal(0x16fd8000L, r.OutFileParts[0].Size);
            Assert.NotNull(r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.Equal("", r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.NotNull(r.OutFileParts[0].FileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", r.OutFileParts[0].FileName);
            Assert.NotNull(r.ResultCrc);
            Assert.Equal(0xab6affa5U, r.ResultCrc.Value);
            Assert.NotNull(r.ResultSize);
            Assert.Equal(0x16fd8000L, r.ResultSize.Value);
            Assert.NotNull(r.Scan);
            Assert.NotNull(r.StepInfo);
            Assert.Equal(VerifyResult.Unverified, r.VerifyResult);
            Assert.Equal("NoVerify", r.VerifyType);

            ////////////////////////////////////////
            // StepResult DatItem
            ////////////////////////////////////////
            Assert.Null(r.MatchedDatItem);

            ////////////////////////////////////////
            // Task Result
            ////////////////////////////////////////
            Assert.Equal(ContainerType.TmdApp, t.ContainerType);
            Assert.Equal(SystemType.WiiU, t.System);
            Assert.Equal(TaskType.Scan, t.Task);
            Assert.Equal(0x16fd8000L, t.Size);
            Assert.Equal(0xab6affa5U, t.CRC);
            Assert.Equal(0x9dad6d51U, t.DecryptedCrc);
            Assert.Equal(VerifyResult.Unverified, t.VerifyResult);
            Assert.Equal(inPath.TrimEnd('\\', '/'), t.InFilePath.TrimEnd('\\', '/'));
            Assert.NotNull(t.OutPath);
            Assert.Equal("", t.OutPath);
            Assert.NotNull(t.Name);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", t.Name);
            Assert.NotNull(t.VerifyType);
            Assert.Equal("NoVerify", t.VerifyType);
            Assert.NotNull(t.VerifyChecksum);
            Assert.Equal("", t.VerifyChecksum);
            Assert.Null(t.DatMatch);
            Assert.Null(t.ErrorMsg);
            Assert.NotNull(t.OutFileName);
            Assert.Equal("", t.OutFileName);
            Assert.Null(t.OutKeyFilePath);
            Assert.NotNull(t.OutScanFilePath);
            Assert.Equal(Path.Combine(basePath, "Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555].nkit.yaml"), t.OutScanFilePath);
            Assert.False(t.HasEncryption);
            Assert.True(t.SupportsEncryption);
            Assert.False(t.ImageSkipped);
            Assert.NotNull(t.Key);
            Assert.Equal("75B928E955968EB352E6B19A9B2E4EBE", t.Key.ToHexString());
            Assert.NotNull(t.StepFiles);
            Assert.Equal(1, t.StepFiles.Count);
            Assert.Equal(0x16fd8000L, t.StepFiles[0].Size);
            Assert.False(t.StepFiles[0].IsIndex);
            Assert.True(t.StepFiles[0].IsImageName);
            Assert.NotNull(t.StepFiles[0].Checksums.ToString(true, true));
            Assert.Equal("", t.StepFiles[0].Checksums.ToString(true, true));
            Assert.NotNull(t.StepFiles[0].FileName);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", t.StepFiles[0].FileName);

            ////////////////////////////////////////
            // Result Scan
            ////////////////////////////////////////
            Assert.NotNull(t.Scan);
            Assert.NotNull(t.Scan.Name);
            Assert.Equal("Pbpbgb Zntvp Pvephf 7 (Rhebcr) (Ra,Se,Qr,Rf,Vg,Ay,Cg) [555055556567Q555]", t.Scan.Name);
            Assert.Equal(SystemType.WiiU, f.SystemType);
            Assert.Equal(0xab6affa5U, t.Scan.Crc);
            Assert.Equal(0x9dad6d51U, t.Scan.CrcDecrypted);
            Assert.Equal(0x16fd8000L, t.Scan.Size);
            Assert.Equal(5080, t.Scan.VirtualFsTotalFileCount);
            Assert.Equal(700, t.Scan.VirtualFsTotalFoldersCount);
            Assert.NotNull(t.Scan.Properties["System"].ToXmlValue());
            Assert.Equal("WiiU", t.Scan.Properties["System"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Media"].ToXmlValue());
            Assert.Equal("APP", t.Scan.Properties["Media"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Type"].ToXmlValue());
            Assert.Equal("Retail", t.Scan.Properties["Type"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Size"].ToXmlValue());
            Assert.Equal("016FD8000", t.Scan.Properties["Size"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["CRC"].ToXmlValue());
            Assert.Equal("AB6AFFA5", t.Scan.Properties["CRC"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal("9DAD6D51", t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal(10, t.Scan.Areas.Count);
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[0].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[0].AreaInfo.Properties["TmdVersion"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[0].AreaInfo.Properties["ContentHeaders"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000000.app", t.Scan.Areas[0].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000000.app", t.Scan.Areas[0].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.Equal("555055556567A555", t.Scan.Areas[0].AreaInfo.Properties["TitleId"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[0].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[0].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[0].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[0].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[0].AreaInfo.Properties["MissingFiles"].ToXmlValue());
            Assert.Equal(AreaType.FstBlock, t.Scan.Areas[0].Type);
            Assert.Equal(0x99089e97U, t.Scan.Areas[0].Crc);
            Assert.Equal(0x0dc68880U, t.Scan.Areas[0].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[0].Size);
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[1].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[1].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000001.app", t.Scan.Areas[1].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000001.app", t.Scan.Areas[1].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[1].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[1].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[1].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[1].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[1].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[1].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[1].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[1].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[1].Type);
            Assert.Equal(0x9ed15493U, t.Scan.Areas[1].Crc);
            Assert.Equal(0xe6c84bffU, t.Scan.Areas[1].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[1].Size);
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[2].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000002.app", t.Scan.Areas[2].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000002.app", t.Scan.Areas[2].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[2].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[2].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[2].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[2].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[2].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[2].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[2].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[2].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[2].Type);
            Assert.Equal(0x0e8c2163U, t.Scan.Areas[2].Crc);
            Assert.Equal(0xec64602bU, t.Scan.Areas[2].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[2].Size);
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[3].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000003.app", t.Scan.Areas[3].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000003.app", t.Scan.Areas[3].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[3].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[3].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[3].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[3].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[3].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[3].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[3].Type);
            Assert.Equal(0x83fc5099U, t.Scan.Areas[3].Crc);
            Assert.Equal(0x4af3f8e5U, t.Scan.Areas[3].CrcDecrypted);
            Assert.Equal(0x30000L, t.Scan.Areas[3].Size);
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("4", t.Scan.Areas[4].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000004.app", t.Scan.Areas[4].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000004.app", t.Scan.Areas[4].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[4].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[4].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[4].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[4].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[4].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[4].Type);
            Assert.Equal(0x8a39f52aU, t.Scan.Areas[4].Crc);
            Assert.Equal(0xbdfcfba8U, t.Scan.Areas[4].CrcDecrypted);
            Assert.Equal(0xb30000L, t.Scan.Areas[4].Size);
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("5", t.Scan.Areas[5].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000005.app", t.Scan.Areas[5].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000005.app", t.Scan.Areas[5].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[5].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[5].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[5].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[5].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[5].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[5].Type);
            Assert.Equal(0xc5c9dfd6U, t.Scan.Areas[5].Crc);
            Assert.Equal(0xef90ac5eU, t.Scan.Areas[5].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[5].Size);
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("6", t.Scan.Areas[6].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000006.app", t.Scan.Areas[6].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000006.app", t.Scan.Areas[6].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[6].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[6].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[6].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[6].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[6].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[6].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[6].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[6].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[6].Type);
            Assert.Equal(0x710b706eU, t.Scan.Areas[6].Crc);
            Assert.Equal(0xfbafc37eU, t.Scan.Areas[6].CrcDecrypted);
            Assert.Equal(0x110000L, t.Scan.Areas[6].Size);
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("7", t.Scan.Areas[7].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000007.app", t.Scan.Areas[7].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000007.app", t.Scan.Areas[7].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[7].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[7].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[7].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[7].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[7].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[7].Type);
            Assert.Equal(0x111e5dbaU, t.Scan.Areas[7].Crc);
            Assert.Equal(0xa761359bU, t.Scan.Areas[7].CrcDecrypted);
            Assert.Equal(0x2090000L, t.Scan.Areas[7].Size);
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[8].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000008.app", t.Scan.Areas[8].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000008.app", t.Scan.Areas[8].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[8].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[8].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000000", t.Scan.Areas[8].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[8].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[8].Type);
            Assert.Equal(0xba219738U, t.Scan.Areas[8].Crc);
            Assert.Equal(0xe3d34cf4U, t.Scan.Areas[8].CrcDecrypted);
            Assert.Equal(0x2a0000L, t.Scan.Areas[8].Size);
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.Equal("9", t.Scan.Areas[9].AreaInfo.Properties["ContentIndex"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["App"].ToXmlValue());
            Assert.Equal("00000009.app", t.Scan.Areas[9].AreaInfo.Properties["App"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.Equal("00000009.app", t.Scan.Areas[9].AreaInfo.Properties["Filename"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00010000", t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[9].AreaInfo.Properties["HashRoot"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[9].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[9].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["TitleKeyMissing"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["SiTitleId"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[9].Type);
            Assert.Equal(0x6a47a018U, t.Scan.Areas[9].Crc);
            Assert.Equal(0xe5b03249U, t.Scan.Areas[9].CrcDecrypted);
            Assert.Equal(0x13f10000L, t.Scan.Areas[9].Size);

            base.Complete();
        }
    }
}