
using Nanook.NKit;
using System;
using System.IO;
using Xunit;

namespace NKit.Tests.Full.Wiped
{
    public partial class WipedImage_Wii_Tests : WipedImageTestsBase
    {
        //Retail     / RVZ       / 8GiB    / Retail with Virtual Console partitions
        [Fact]
        public void Fhcre_Fznfu_Oebf_Oenjy_Rhebcr_Ra_Se_Qr_Rf_Vg_rvz_ConvertRvz()
        {
            string fileName = @"Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz";
            string inPath = Path.GetFullPath(Path.Combine(@"../../../../../WipedImages", "Wii"));
            string outFolderName = $"Wii_Fhcre_Fznfu_Oebf_Oenjy_Rhebcr_Ra_Se_Qr_Rf_Vg_rvz_ConvertRvz_{Guid.NewGuid():N}";
            string basePath = Directory.CreateDirectory(Path.Combine(".", outFolderName)).FullName;
            string dats = @"";
            string keys = @"";
            string fixInfo = @"";
            string fixFiles = @"";

            SystemPresetSettings presets = base.CreatePresets("Convert", @"rvz", inPath, fileName, outFolderName, dats, keys, fixInfo, fixFiles);
            //presets.System = SystemType.Wii;

            NKitTaskResults t = base.ProcessImage(presets);
            NKitStepResult r = t.StepResults[0].Result;
            SourceFile f = t.Source;
            IStepInfo i = r.StepInfo;
            Scan s = t.Scan;

            ////////////////////////////////////////
            // Source File
            ////////////////////////////////////////
            Assert.NotNull(f);
            Assert.Equal(inPath.TrimEnd('\\', '/'), f.BasePath.TrimEnd('\\', '/'));
            Assert.NotNull(f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz", f.FriendlyFullPath.Replace(f.BasePath, ""));
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg)", f.CleanName);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg)", f.Name);
            Assert.Equal(SourceImageType.Rvz, f.ImageType);
            Assert.Equal(SourceFileResult.Valid, f.Status);
            Assert.Equal(SystemType.Wii, f.SystemType);
            Assert.False(f.IsArchive);
            Assert.False(f.IsArchived);
            Assert.False(f.IsDeleted);
            Assert.False(f.IsFolderMode);
            Assert.False(f.IsSplitArchive);
            Assert.False(f.IsSplitImage);
            Assert.Equal(0x0L, f.Length);
            Assert.Equal(1, f.ImageFiles.Length);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz", f.ImageFiles[0].FileName);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg)", f.ImageFiles[0].NameOnly);
            Assert.Equal(".rvz", f.ImageFiles[0].Extension);
            Assert.Equal(0x2bbad0L, f.ImageFiles[0].Size);
            Assert.False(f.ImageFiles[0].IsArchived);
            Assert.Equal(SourceArchiveType.None, f.ArchiveType);
            Assert.Null(f.ArchiveFiles);
            Assert.Null(f.Key);
            // f.IndexFile IndexFile Test
            Assert.Null(f.IndexFile);

            ////////////////////////////////////////
            // Step Info
            ////////////////////////////////////////
            Assert.NotNull(i);
            Assert.False(i.CanCrc);
            Assert.False(i.CanHash);
            Assert.True(i.CreateInChecksum);
            Assert.False(i.CreateOutChecksum);
            Assert.True(i.CreateScan);
            Assert.False(i.DeleteSourceCandidate);
            Assert.True(i.FullScan);
            Assert.False(i.IsExpand);
            Assert.False(i.IsFix);
            Assert.False(i.IsLossy);
            Assert.True(i.WriteImage);
            Assert.Equal("Convert-WiiGc-Lossless", i.Name);
            Assert.Equal(OutputType.Image, i.OutputType);
            Assert.True(i.ReqChk);
            Assert.False(i.ReqPatch);
            Assert.Equal(TaskType.Convert, i.StepType);
            Assert.Equal(VerifyMethod.NoVerify, i.VerifyMethod);
            Assert.Null(i.VerifyChecksums);
            Assert.NotNull(i.Config);
            Assert.Equal("rvz[nkit]/wbfs[nkit]/ciso[nkit]", i.Config);
            Assert.NotNull(i.ImageConfig);
            Assert.Equal("rvz[nkit]", i.ImageConfig);
            Assert.NotNull(i.SrcParts);
            Assert.Equal(1, i.SrcParts.Length);
            Assert.Equal(0x1fb4e0000L, i.SrcParts[0].Size);
            Assert.NotNull(i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:61284D76, Md5:17F2192BB27DDE87CDB3F3D60C5696CF, Sha1:D455AFBFAE33426F0DFB70ED8A271BCFBE42DB6A, XxHash:ADE77CDF70F0A9CD", i.SrcParts[0].Checksums.ToString(true, true));
            Assert.Null(i.SrcParts[0].FileName);

            ////////////////////////////////////////
            // Source Scan
            ////////////////////////////////////////
            Assert.Null(i.SrcScan);

            ////////////////////////////////////////
            // Source DatItem
            ////////////////////////////////////////
            Assert.Null(i.DatMatch);

            ////////////////////////////////////////
            // Step Result
            ////////////////////////////////////////
            Assert.NotNull(r);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz", r.FinalName);
            Assert.Null(r.ChkCompared);
            Assert.NotNull(r.InFileParts);
            Assert.Equal(1, r.InFileParts.Length);
            Assert.Equal(0x1fb4e0000L, r.InFileParts[0].Size);
            Assert.NotNull(r.InFileParts[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:61284D76, Md5:17F2192BB27DDE87CDB3F3D60C5696CF, Sha1:D455AFBFAE33426F0DFB70ED8A271BCFBE42DB6A, XxHash:ADE77CDF70F0A9CD", r.InFileParts[0].Checksums.ToString(true, true));
            Assert.Null(r.InFileParts[0].FileName);
            Assert.NotNull(r.OutFileParts);
            Assert.Equal(1, r.OutFileParts.Length);
            Assert.Equal(0x2bbad0L, r.OutFileParts[0].Size);
            Assert.NotNull(r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:46DFC3FB", r.OutFileParts[0].Checksums.ToString(true, true));
            Assert.NotNull(r.OutFileParts[0].FileName);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz~", r.OutFileParts[0].FileName);
            Assert.NotNull(r.ResultCrc);
            Assert.Equal(0x61284d76U, r.ResultCrc.Value);
            Assert.NotNull(r.ResultSize);
            Assert.Equal(0x1fb4e0000L, r.ResultSize.Value);
            Assert.NotNull(r.Scan);
            Assert.NotNull(r.StepInfo);
            Assert.Equal(VerifyResult.Unverified, r.VerifyResult);
            Assert.Equal("NoVerify", r.VerifyType);

            ////////////////////////////////////////
            // StepResult DatItem
            ////////////////////////////////////////
            Assert.Null(r.MatchedDatItem);

            ////////////////////////////////////////
            // Task Result
            ////////////////////////////////////////
            Assert.Equal(ContainerType.Rvz, t.ContainerType);
            Assert.Equal(SystemType.Wii, t.System);
            Assert.Equal(TaskType.Convert, t.Task);
            Assert.Equal(0x1fb4e0000L, t.Size);
            Assert.Equal(0x61284d76U, t.CRC);
            Assert.Equal(0xafda5867U, t.DecryptedCrc);
            Assert.Equal(VerifyResult.Unverified, t.VerifyResult);
            Assert.Equal(inPath.TrimEnd('\\', '/'), t.InFilePath.TrimEnd('\\', '/'));
            Assert.Equal(basePath.TrimEnd('\\', '/'), t.OutPath.TrimEnd('\\', '/'));
            Assert.NotNull(t.Name);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg)", t.Name);
            Assert.NotNull(t.VerifyType);
            Assert.Equal("NoVerify", t.VerifyType);
            Assert.NotNull(t.VerifyChecksum);
            Assert.Equal("", t.VerifyChecksum);
            Assert.Null(t.DatMatch);
            Assert.Null(t.ErrorMsg);
            Assert.NotNull(t.OutFileName);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz", t.OutFileName);
            Assert.Null(t.OutKeyFilePath);
            Assert.NotNull(t.OutScanFilePath);
            Assert.Equal(Path.Combine(basePath, "Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).nkit.yaml"), t.OutScanFilePath);
            Assert.False(t.HasEncryption);
            Assert.True(t.SupportsEncryption);
            Assert.False(t.ImageSkipped);
            Assert.Null(t.Key);
            Assert.NotNull(t.StepFiles);
            Assert.Equal(1, t.StepFiles.Count);
            Assert.Equal(0x2bbad0L, t.StepFiles[0].Size);
            Assert.False(t.StepFiles[0].IsIndex);
            Assert.True(t.StepFiles[0].IsImageName);
            Assert.NotNull(t.StepFiles[0].Checksums.ToString(true, true));
            Assert.Equal("Crc32:46DFC3FB", t.StepFiles[0].Checksums.ToString(true, true));
            Assert.NotNull(t.StepFiles[0].FileName);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg).rvz~", t.StepFiles[0].FileName);

            ////////////////////////////////////////
            // Result Scan
            ////////////////////////////////////////
            Assert.NotNull(t.Scan);
            Assert.NotNull(t.Scan.Name);
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy (Rhebcr) (Ra,Se,Qr,Rf,Vg)", t.Scan.Name);
            Assert.Equal(SystemType.Wii, f.SystemType);
            Assert.Equal(0x61284d76U, t.Scan.Crc);
            Assert.Equal(0xafda5867U, t.Scan.CrcDecrypted);
            Assert.Equal(0x1fb4e0000L, t.Scan.Size);
            Assert.Equal(13451, t.Scan.VirtualFsTotalFileCount);
            Assert.Equal(639, t.Scan.VirtualFsTotalFoldersCount);
            Assert.NotNull(t.Scan.Properties["System"].ToXmlValue());
            Assert.Equal("Wii", t.Scan.Properties["System"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Media"].ToXmlValue());
            Assert.Equal("Disc", t.Scan.Properties["Media"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Type"].ToXmlValue());
            Assert.Equal("Retail", t.Scan.Properties["Type"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["Size"].ToXmlValue());
            Assert.Equal("1FB4E0000", t.Scan.Properties["Size"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["CRC"].ToXmlValue());
            Assert.Equal("61284D76", t.Scan.Properties["CRC"].ToXmlValue());
            Assert.NotNull(t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal("AFDA5867", t.Scan.Properties["DecryptedCRC"].ToXmlValue());
            Assert.Equal(38, t.Scan.Areas.Count);
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("EFOC56", t.Scan.Areas[0].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[0].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[0].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Region"].ToXmlValue());
            Assert.Equal("Pal", t.Scan.Areas[0].AreaInfo.Properties["Region"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy", t.Scan.Areas[0].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[0].AreaInfo.Properties["Partitions"].ToXmlValue());
            Assert.Equal("15", t.Scan.Areas[0].AreaInfo.Properties["Partitions"].ToXmlValue());
            Assert.Equal(AreaType.ImageHeader, t.Scan.Areas[0].Type);
            Assert.Equal(0x5d42f726U, t.Scan.Areas[0].Crc);
            Assert.Equal(0x5d42f726U, t.Scan.Areas[0].CrcDecrypted);
            Assert.Equal(0x50000L, t.Scan.Areas[0].Size);
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[1].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Update", t.Scan.Areas[1].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("CD0411364EDB14768FDD6FB03A4C6AC9914CC7EA", t.Scan.Areas[1].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[1].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[1].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[1].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[1].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[1].Type);
            Assert.Equal(0x56151587U, t.Scan.Areas[1].Crc);
            Assert.Equal(0x56151587U, t.Scan.Areas[1].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[1].Size);
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[2].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("ERYFNO", t.Scan.Areas[2].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[2].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[2].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("Fnzcyr Tnzr Anzr", t.Scan.Areas[2].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[2].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[2].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[2].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[2].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("EBAA1940", t.Scan.Areas[2].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("ERYF", t.Scan.Areas[2].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("00003E398", t.Scan.Areas[2].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[2].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("00A8C0000", t.Scan.Areas[2].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[2].Type);
            Assert.Equal(0xb2b0f726U, t.Scan.Areas[2].Crc);
            Assert.Equal(0x5b8e8774U, t.Scan.Areas[2].CrcDecrypted);
            Assert.Equal(0xae38000L, t.Scan.Areas[2].Size);
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[3].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[3].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[3].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[3].Type);
            Assert.Equal(0x1c2b2d3eU, t.Scan.Areas[3].Crc);
            Assert.Equal(0x1c2b2d3eU, t.Scan.Areas[3].CrcDecrypted);
            Assert.Equal(0x4958000L, t.Scan.Areas[3].Size);
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[4].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("Game", t.Scan.Areas[4].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("0B5D094054A32821FC6768EB6FD752D0A2816441", t.Scan.Areas[4].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[4].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[4].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[4].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[4].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[4].Type);
            Assert.Equal(0x477c30b9U, t.Scan.Areas[4].Crc);
            Assert.Equal(0x477c30b9U, t.Scan.Areas[4].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[4].Size);
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("1", t.Scan.Areas[5].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("EFOC56", t.Scan.Areas[5].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[5].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[5].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("Fhcre Fznfu Oebf. Oenjy", t.Scan.Areas[5].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[5].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[5].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[5].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[5].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("CD6D3AD4", t.Scan.Areas[5].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[5].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("00050193C", t.Scan.Areas[5].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[5].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("1BC7C0000", t.Scan.Areas[5].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[5].Type);
            Assert.Equal(0xa155ddd5U, t.Scan.Areas[5].Crc);
            Assert.Equal(0xa355c3beU, t.Scan.Areas[5].CrcDecrypted);
            Assert.Equal(0x1cad30000L, t.Scan.Areas[5].Size);
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[6].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UN3C", t.Scan.Areas[6].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("E18663A2A6868620329C6657FEC3631D09F57D81", t.Scan.Areas[6].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[6].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[6].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[6].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[6].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[6].Type);
            Assert.Equal(0x54afb995U, t.Scan.Areas[6].Crc);
            Assert.Equal(0x54afb995U, t.Scan.Areas[6].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[6].Size);
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("2", t.Scan.Areas[7].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UN3C56", t.Scan.Areas[7].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[7].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[7].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[7].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[7].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[7].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[7].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[7].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("787A2415", t.Scan.Areas[7].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UN3C", t.Scan.Areas[7].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("000187820", t.Scan.Areas[7].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[7].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000A28000", t.Scan.Areas[7].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[7].Type);
            Assert.Equal(0xa41bbbebU, t.Scan.Areas[7].Crc);
            Assert.Equal(0xbac9df87U, t.Scan.Areas[7].CrcDecrypted);
            Assert.Equal(0xa80000L, t.Scan.Areas[7].Size);
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[8].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UN4C", t.Scan.Areas[8].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("391066592F53039F12141FC331BDFF0D1D27FE3B", t.Scan.Areas[8].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[8].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[8].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[8].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[8].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[8].Type);
            Assert.Equal(0xbcddf92eU, t.Scan.Areas[8].Crc);
            Assert.Equal(0xbcddf92eU, t.Scan.Areas[8].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[8].Size);
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("3", t.Scan.Areas[9].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UN4C56", t.Scan.Areas[9].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[9].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[9].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[9].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[9].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[9].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[9].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[9].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("424A9E23", t.Scan.Areas[9].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UN4C", t.Scan.Areas[9].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("00018B820", t.Scan.Areas[9].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[9].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000A38000", t.Scan.Areas[9].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[9].Type);
            Assert.Equal(0x54810e68U, t.Scan.Areas[9].Crc);
            Assert.Equal(0xc78bd61eU, t.Scan.Areas[9].CrcDecrypted);
            Assert.Equal(0xa90000L, t.Scan.Areas[9].Size);
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("4", t.Scan.Areas[10].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UONC", t.Scan.Areas[10].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("CA7590D40903BDE240A01825D4CDDA2D292D4E41", t.Scan.Areas[10].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[10].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[10].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[10].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[10].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[10].Type);
            Assert.Equal(0x72625ca0U, t.Scan.Areas[10].Crc);
            Assert.Equal(0x72625ca0U, t.Scan.Areas[10].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[10].Size);
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("4", t.Scan.Areas[11].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UONC56", t.Scan.Areas[11].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[11].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[11].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[11].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[11].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[11].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[11].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[11].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("CEABC68E", t.Scan.Areas[11].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UONC", t.Scan.Areas[11].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001A7120", t.Scan.Areas[11].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[11].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000A50000", t.Scan.Areas[11].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[11].Type);
            Assert.Equal(0x119e0661U, t.Scan.Areas[11].Crc);
            Assert.Equal(0x7ee90ab5U, t.Scan.Areas[11].CrcDecrypted);
            Assert.Equal(0xaa8000L, t.Scan.Areas[11].Size);
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[12].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("4", t.Scan.Areas[12].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[12].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[12].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[12].Type);
            Assert.Equal(0xc01d2f2cU, t.Scan.Areas[12].Crc);
            Assert.Equal(0xc01d2f2cU, t.Scan.Areas[12].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[12].Size);
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("5", t.Scan.Areas[13].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOOS", t.Scan.Areas[13].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("043B5AC7B1A6DFB0092A0A5B46C8387BA6B3E971", t.Scan.Areas[13].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[13].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[13].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[13].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[13].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[13].Type);
            Assert.Equal(0xd504c4dfU, t.Scan.Areas[13].Crc);
            Assert.Equal(0xd504c4dfU, t.Scan.Areas[13].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[13].Size);
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("5", t.Scan.Areas[14].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOOS56", t.Scan.Areas[14].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[14].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[14].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[14].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[14].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[14].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[14].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[14].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("EF2D8678", t.Scan.Areas[14].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOOS", t.Scan.Areas[14].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("000244F20", t.Scan.Areas[14].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[14].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000AF0000", t.Scan.Areas[14].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[14].Type);
            Assert.Equal(0x2a91532eU, t.Scan.Areas[14].Crc);
            Assert.Equal(0xcede667aU, t.Scan.Areas[14].CrcDecrypted);
            Assert.Equal(0xb50000L, t.Scan.Areas[14].Size);
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("6", t.Scan.Areas[15].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOOC", t.Scan.Areas[15].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("D37536C6512B4D3516C0847430AB5CFD2F29291B", t.Scan.Areas[15].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[15].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[15].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[15].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[15].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[15].Type);
            Assert.Equal(0xb93ca3c8U, t.Scan.Areas[15].Crc);
            Assert.Equal(0xb93ca3c8U, t.Scan.Areas[15].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[15].Size);
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("6", t.Scan.Areas[16].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOOC56", t.Scan.Areas[16].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[16].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[16].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[16].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[16].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[16].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[16].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[16].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("A6FBAD14", t.Scan.Areas[16].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOOC", t.Scan.Areas[16].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("000245820", t.Scan.Areas[16].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[16].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000AF0000", t.Scan.Areas[16].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[16].Type);
            Assert.Equal(0xd36b54bfU, t.Scan.Areas[16].Crc);
            Assert.Equal(0x01290d19U, t.Scan.Areas[16].CrcDecrypted);
            Assert.Equal(0xb50000L, t.Scan.Areas[16].Size);
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("7", t.Scan.Areas[17].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOPC", t.Scan.Areas[17].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("E32EEA04B48C338E05C48ACEF4C0EF88235E8F00", t.Scan.Areas[17].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[17].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[17].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[17].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[17].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[17].Type);
            Assert.Equal(0x9e0b9d68U, t.Scan.Areas[17].Crc);
            Assert.Equal(0x9e0b9d68U, t.Scan.Areas[17].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[17].Size);
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("7", t.Scan.Areas[18].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOPC56", t.Scan.Areas[18].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[18].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[18].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[18].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[18].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[18].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[18].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[18].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("86A375FA", t.Scan.Areas[18].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOPC", t.Scan.Areas[18].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001A7520", t.Scan.Areas[18].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[18].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000A50000", t.Scan.Areas[18].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[18].Type);
            Assert.Equal(0xc01fcf2fU, t.Scan.Areas[18].Crc);
            Assert.Equal(0x4832d3d0U, t.Scan.Areas[18].CrcDecrypted);
            Assert.Equal(0xaa8000L, t.Scan.Areas[18].Size);
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[19].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("7", t.Scan.Areas[19].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[19].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[19].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[19].Type);
            Assert.Equal(0xb49905f1U, t.Scan.Areas[19].Crc);
            Assert.Equal(0xb49905f1U, t.Scan.Areas[19].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[19].Size);
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[20].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOQC", t.Scan.Areas[20].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("67761088FAECE629E615A3237B6F6CB55CFF81E9", t.Scan.Areas[20].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[20].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[20].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[20].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[20].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[20].Type);
            Assert.Equal(0xbf1299eaU, t.Scan.Areas[20].Crc);
            Assert.Equal(0xbf1299eaU, t.Scan.Areas[20].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[20].Size);
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[21].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOQC56", t.Scan.Areas[21].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[21].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[21].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[21].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[21].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[21].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[21].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[21].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("8734F3C6", t.Scan.Areas[21].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOQC", t.Scan.Areas[21].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("000187820", t.Scan.Areas[21].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[21].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000A30000", t.Scan.Areas[21].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[21].Type);
            Assert.Equal(0x4099ec81U, t.Scan.Areas[21].Crc);
            Assert.Equal(0x83171b07U, t.Scan.Areas[21].CrcDecrypted);
            Assert.Equal(0xa88000L, t.Scan.Areas[21].Size);
            Assert.NotNull(t.Scan.Areas[22].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[22].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[22].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("8", t.Scan.Areas[22].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[22].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[22].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[22].Type);
            Assert.Equal(0x5cf30470U, t.Scan.Areas[22].Crc);
            Assert.Equal(0x5cf30470U, t.Scan.Areas[22].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[22].Size);
            Assert.NotNull(t.Scan.Areas[23].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("9", t.Scan.Areas[23].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[23].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UORC", t.Scan.Areas[23].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[23].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("C539AC7F58EA2DD92FDF77338D278BA031642D34", t.Scan.Areas[23].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[23].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[23].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[23].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[23].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[23].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[23].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[23].Type);
            Assert.Equal(0x06643c10U, t.Scan.Areas[23].Crc);
            Assert.Equal(0x06643c10U, t.Scan.Areas[23].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[23].Size);
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("9", t.Scan.Areas[24].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UORC56", t.Scan.Areas[24].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[24].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[24].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[24].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[24].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[24].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[24].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[24].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("8632425B", t.Scan.Areas[24].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UORC", t.Scan.Areas[24].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001C5520", t.Scan.Areas[24].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[24].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000A78000", t.Scan.Areas[24].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[24].Type);
            Assert.Equal(0x2d6c355eU, t.Scan.Areas[24].Crc);
            Assert.Equal(0x7b001debU, t.Scan.Areas[24].CrcDecrypted);
            Assert.Equal(0xad0000L, t.Scan.Areas[24].Size);
            Assert.NotNull(t.Scan.Areas[25].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[25].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[25].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOSC", t.Scan.Areas[25].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[25].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("45C59CA7356A3FE3C3296476DCDAEC81311BB800", t.Scan.Areas[25].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[25].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[25].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[25].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[25].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[25].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[25].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[25].Type);
            Assert.Equal(0xabed1204U, t.Scan.Areas[25].Crc);
            Assert.Equal(0xabed1204U, t.Scan.Areas[25].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[25].Size);
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[26].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOSC56", t.Scan.Areas[26].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[26].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[26].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[26].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[26].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[26].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[26].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[26].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("0F4587BB", t.Scan.Areas[26].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOSC", t.Scan.Areas[26].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001BFE74", t.Scan.Areas[26].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[26].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000B68000", t.Scan.Areas[26].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[26].Type);
            Assert.Equal(0x514a3df9U, t.Scan.Areas[26].Crc);
            Assert.Equal(0xf6b711f1U, t.Scan.Areas[26].CrcDecrypted);
            Assert.Equal(0xbc8000L, t.Scan.Areas[26].Size);
            Assert.NotNull(t.Scan.Areas[27].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[27].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[27].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("10", t.Scan.Areas[27].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[27].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[27].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[27].Type);
            Assert.Equal(0x48404831U, t.Scan.Areas[27].Crc);
            Assert.Equal(0x48404831U, t.Scan.Areas[27].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[27].Size);
            Assert.NotNull(t.Scan.Areas[28].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("11", t.Scan.Areas[28].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[28].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOTC", t.Scan.Areas[28].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[28].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("A2EBFB049F566EE58E7474908C54EFF0B1755BA7", t.Scan.Areas[28].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[28].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[28].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[28].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[28].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[28].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[28].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[28].Type);
            Assert.Equal(0x8bf067b7U, t.Scan.Areas[28].Crc);
            Assert.Equal(0x8bf067b7U, t.Scan.Areas[28].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[28].Size);
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("11", t.Scan.Areas[29].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOTC56", t.Scan.Areas[29].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[29].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[29].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[29].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[29].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[29].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[29].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[29].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("9E065145", t.Scan.Areas[29].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOTC", t.Scan.Areas[29].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001BFC74", t.Scan.Areas[29].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[29].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000B60000", t.Scan.Areas[29].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[29].Type);
            Assert.Equal(0x82dc75b9U, t.Scan.Areas[29].Crc);
            Assert.Equal(0x5b5d5efdU, t.Scan.Areas[29].CrcDecrypted);
            Assert.Equal(0xbc0000L, t.Scan.Areas[29].Size);
            Assert.NotNull(t.Scan.Areas[30].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("12", t.Scan.Areas[30].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[30].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOVC", t.Scan.Areas[30].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[30].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("04CB2FE53339803C99EF987B62711173FD9E99A2", t.Scan.Areas[30].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[30].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[30].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[30].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[30].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[30].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[30].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[30].Type);
            Assert.Equal(0xcee70db2U, t.Scan.Areas[30].Crc);
            Assert.Equal(0xcee70db2U, t.Scan.Areas[30].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[30].Size);
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("12", t.Scan.Areas[31].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOVC56", t.Scan.Areas[31].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[31].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[31].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[31].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[31].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[31].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[31].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[31].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("00030F5A", t.Scan.Areas[31].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOVC", t.Scan.Areas[31].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001BFD74", t.Scan.Areas[31].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[31].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("000F60000", t.Scan.Areas[31].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[31].Type);
            Assert.Equal(0xa2053a2cU, t.Scan.Areas[31].Crc);
            Assert.Equal(0x2d80b571U, t.Scan.Areas[31].CrcDecrypted);
            Assert.Equal(0xfe0000L, t.Scan.Areas[31].Size);
            Assert.NotNull(t.Scan.Areas[32].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("13", t.Scan.Areas[32].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[32].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOXC", t.Scan.Areas[32].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[32].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("78660456679A65B689BD9736705BF4AFAB5DBD15", t.Scan.Areas[32].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[32].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[32].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[32].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[32].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[32].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[32].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[32].Type);
            Assert.Equal(0x677bfc15U, t.Scan.Areas[32].Crc);
            Assert.Equal(0x677bfc15U, t.Scan.Areas[32].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[32].Size);
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("13", t.Scan.Areas[33].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOXCMM", t.Scan.Areas[33].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[33].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[33].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("Bpnevan RH Cnegvgvba", t.Scan.Areas[33].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[33].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[33].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[33].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[33].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("876AB971", t.Scan.Areas[33].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOXC", t.Scan.Areas[33].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001D6DB4", t.Scan.Areas[33].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[33].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("0036C0000", t.Scan.Areas[33].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[33].Type);
            Assert.Equal(0x3cd1e159U, t.Scan.Areas[33].Crc);
            Assert.Equal(0x1a95e096U, t.Scan.Areas[33].CrcDecrypted);
            Assert.Equal(0x3888000L, t.Scan.Areas[33].Size);
            Assert.NotNull(t.Scan.Areas[34].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[34].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[34].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("13", t.Scan.Areas[34].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[34].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[34].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[34].Type);
            Assert.Equal(0x2cea2b3cU, t.Scan.Areas[34].Crc);
            Assert.Equal(0x2cea2b3cU, t.Scan.Areas[34].CrcDecrypted);
            Assert.Equal(0x8000L, t.Scan.Areas[34].Size);
            Assert.NotNull(t.Scan.Areas[35].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("14", t.Scan.Areas[35].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[35].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.Equal("UOYC", t.Scan.Areas[35].AreaInfo.Properties["PartitionType"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[35].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.Equal("5E0E2E12F3534234C4AE14CD4D8D11D1767A7463", t.Scan.Areas[35].AreaInfo.Properties["ContentSha"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[35].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.Equal("CECEE288", t.Scan.Areas[35].AreaInfo.Properties["CommonKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[35].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.Equal("ECBB4B55", t.Scan.Areas[35].AreaInfo.Properties["TitleKeyCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[35].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal("Valid", t.Scan.Areas[35].AreaInfo.Properties["Signed"].ToXmlValue());
            Assert.Equal(AreaType.PartitionHeader, t.Scan.Areas[35].Type);
            Assert.Equal(0xa4350aafU, t.Scan.Areas[35].Crc);
            Assert.Equal(0xa4350aafU, t.Scan.Areas[35].CrcDecrypted);
            Assert.Equal(0x20000L, t.Scan.Areas[35].Size);
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("14", t.Scan.Areas[36].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.Equal("UOYCMM", t.Scan.Areas[36].AreaInfo.Properties["ID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[36].AreaInfo.Properties["DiscNo"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.Equal("0", t.Scan.Areas[36].AreaInfo.Properties["Revision"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.Equal("FgneSbk RH Cnegvgvba", t.Scan.Areas[36].AreaInfo.Properties["Title"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[36].AreaInfo.Properties["Encrypted"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.Equal("00008000", t.Scan.Areas[36].AreaInfo.Properties["BlockSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.Equal("00000400", t.Scan.Areas[36].AreaInfo.Properties["HashSize"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.Equal("true", t.Scan.Areas[36].AreaInfo.Properties["HasFileSystem"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.Equal("1E2B46F7", t.Scan.Areas[36].AreaInfo.Properties["SystemDataCrc"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("UOYC", t.Scan.Areas[36].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.Equal("0001D6FC0", t.Scan.Areas[36].AreaInfo.Properties["JunkLeadingNulls"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[36].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal("0022E0000", t.Scan.Areas[36].AreaInfo.Properties["JunkEndNullsOffset"].ToXmlValue());
            Assert.Equal(AreaType.FileSystem, t.Scan.Areas[36].Type);
            Assert.Equal(0x8181f5d1U, t.Scan.Areas[36].Crc);
            Assert.Equal(0x3615421aU, t.Scan.Areas[36].CrcDecrypted);
            Assert.Equal(0x2400000L, t.Scan.Areas[36].Size);
            Assert.NotNull(t.Scan.Areas[37].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.Equal("", t.Scan.Areas[37].AreaInfo.Properties["UpdatePartitionRemoved"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[37].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.Equal("14", t.Scan.Areas[37].AreaInfo.Properties["Partition"].ToXmlValue());
            Assert.NotNull(t.Scan.Areas[37].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal("EFOC", t.Scan.Areas[37].AreaInfo.Properties["JunkID"].ToXmlValue());
            Assert.Equal(AreaType.Other, t.Scan.Areas[37].Type);
            Assert.Equal(0x8846bacaU, t.Scan.Areas[37].Crc);
            Assert.Equal(0x8846bacaU, t.Scan.Areas[37].CrcDecrypted);
            Assert.Equal(0x13380000L, t.Scan.Areas[37].Size);

            base.Complete();
        }
    }
}